---
interface_configs:
  - name: GigabitEthernet0/0
    description: MGMT
    ipv4_address: 192.168.1.201/24

  - name: GigabitEthernet0/1
    description: Connects to R6
    ipv4_address: 10.1.6.1/24

  - name: GigabitEthernet0/2
    description: Connects to R7
    ipv4_address: 10.1.7.1/24

  - name: GigabitEthernet0/3
    description: Connects to R8
    ipv4_address: 10.1.8.1/24

  - name: GigabitEthernet0/4
    description: Connects to R2
    ipv4_address: 10.1.2.1/24
